[package]
name = "ntd-assimilation"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
base64ct = "=1.6.0"
ed25519-dalek = "=2.1.1"
ntd-capsule = { path = "../ntd-capsule" }
ntd-core = { path = "../ntd-core" }
ntd-ir = { path = "../ntd-ir" }
ntd-runtime = { path = "../ntd-runtime" }
zeroize = "=1.8.1"
zeroize_derive = "=1.4.2"

[lints]
workspace = true
