[package]
name = "ntd-validation"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ntd-capsule = { path = "../ntd-capsule" }
ntd-core = { path = "../ntd-core" }
ntd-ir = { path = "../ntd-ir" }
ntd-mobile-shell = { path = "../ntd-mobile-shell" }
ntd-runtime = { path = "../ntd-runtime" }

[lints]
workspace = true
